import os
import tempfile
from backend.core.pdf import html_to_pdf


SAMPLE_HTML = """<!DOCTYPE html>
<html><head><meta charset="UTF-8"><style>
  body { font-family: Arial; padding: 2cm; color: #333; }
  h1 { color: #2563EB; }
</style></head><body>
  <h1>Hello World</h1>
  <p>This is a test PDF generated by Playwright.</p>
</body></html>"""


def test_html_to_pdf_creates_file():
    with tempfile.NamedTemporaryFile(suffix=".pdf", delete=False) as f:
        out = f.name
    try:
        html_to_pdf(SAMPLE_HTML, out)
        assert os.path.exists(out)
        size = os.path.getsize(out)
        assert size > 1000, f"PDF too small: {size} bytes"
    finally:
        if os.path.exists(out):
            os.unlink(out)


def test_html_to_pdf_returns_valid_pdf():
    with tempfile.NamedTemporaryFile(suffix=".pdf", delete=False) as f:
        out = f.name
    try:
        html_to_pdf(SAMPLE_HTML, out)
        with open(out, "rb") as f:
            header = f.read(5)
        assert header == b"%PDF-", f"Invalid PDF header: {header}"
    finally:
        if os.path.exists(out):
            os.unlink(out)
